AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Person Lambda API

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Timeout: 29

Resources:
  PersonAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  PersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.serverlessapi.StreamLambdaHandler
      CodeUri: target/DKJMatrix-0.0.1-SNAPSHOT-lambda-package.zip
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref PersonAPI

Outputs:
  PersonEndpoint:
    Description: API Gateway Person Endpoint
    Value:
      Fn::Sub: https://${PersonAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/